// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-200]
	_ = x[BusinessError-400]
	_ = x[InternalServerError-500]
}

const (
	_ErrCode_name_0 = "success"
	_ErrCode_name_1 = "business error"
	_ErrCode_name_2 = "internal server error"
)

func (i ErrCode) String() string {
	switch {
	case i == 200:
		return _ErrCode_name_0
	case i == 400:
		return _ErrCode_name_1
	case i == 500:
		return _ErrCode_name_2
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
